### ISSUE TITLE
The "Select Courses to copy activity to" does not offer any courses

### ISSUE THREAD

**Issue by mudrd8mz** [doiphode/moodle-block_bulkactivity#5]
I have a user who is a teacher in two courses. Being logged in as the user, no potential target course is shown:

![image](https://user-images.githubusercontent.com/85831/81967936-f9f3a880-961b-11ea-81c6-02b87c973d10.png)

**Comment by doiphode** [comment]
Hi, thanks for testing this plugin. Which version of Moodle are you trying this on, so that I can try to replicate? This screenshot is from v3.8
![image](https://user-images.githubusercontent.com/9589814/82765605-2a072c80-9e10-11ea-84fb-42b51536cd7f.png)

Try collapsing and expanding the category again to see the courses.
